name: gp_immo_frontend
version: 0.1.0
description: Mocked Flutter front-end for GP Immo
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2
  sqflite_common_ffi_web: ^0.4.2+1
  path: ^1.9.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1
  geolocator: ^10.1.0
  flutter_local_notifications: ^16.3.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "gop-logo.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "gop-logo.png"
    background_color: "#FFFFFF"
    theme_color: "#E37A5C"

flutter:
  uses-material-design: true
  assets:
    - gop-logo.png
